/**
 * Games supported by the Team Randomizer, mapped to their PokéAPI regional
 * Pokédex. Shared between the server action and the client UI.
 */
export const RANDOMIZER_GAMES: { version: string; label: string; pokedexId: number }[] = [
  { version: "scarlet", label: "Pokémon Scarlet", pokedexId: 25 },
  { version: "violet", label: "Pokémon Violet", pokedexId: 25 },
  { version: "legends-arceus", label: "Pokémon Legends: Arceus", pokedexId: 24 },
  { version: "sword", label: "Pokémon Sword", pokedexId: 20 },
  { version: "shield", label: "Pokémon Shield", pokedexId: 20 },
  { version: "brilliant-diamond", label: "Pokémon Brilliant Diamond", pokedexId: 5 },
  { version: "shining-pearl", label: "Pokémon Shining Pearl", pokedexId: 5 },
  { version: "lets-go-pikachu", label: "Let's Go, Pikachu!", pokedexId: 2 },
  { version: "lets-go-eevee", label: "Let's Go, Eevee!", pokedexId: 2 },
  { version: "ultra-sun", label: "Pokémon Ultra Sun", pokedexId: 16 },
  { version: "ultra-moon", label: "Pokémon Ultra Moon", pokedexId: 16 },
  { version: "sun", label: "Pokémon Sun", pokedexId: 15 },
  { version: "moon", label: "Pokémon Moon", pokedexId: 15 },
  { version: "omega-ruby", label: "Pokémon Omega Ruby", pokedexId: 14 },
  { version: "alpha-sapphire", label: "Pokémon Alpha Sapphire", pokedexId: 14 },
  { version: "x", label: "Pokémon X", pokedexId: 11 },
  { version: "y", label: "Pokémon Y", pokedexId: 11 },
  { version: "black-2", label: "Pokémon Black 2", pokedexId: 9 },
  { version: "white-2", label: "Pokémon White 2", pokedexId: 9 },
  { version: "black", label: "Pokémon Black", pokedexId: 8 },
  { version: "white", label: "Pokémon White", pokedexId: 8 },
  { version: "heartgold", label: "Pokémon HeartGold", pokedexId: 7 },
  { version: "soulsilver", label: "Pokémon SoulSilver", pokedexId: 7 },
  { version: "platinum", label: "Pokémon Platinum", pokedexId: 6 },
  { version: "diamond", label: "Pokémon Diamond", pokedexId: 5 },
  { version: "pearl", label: "Pokémon Pearl", pokedexId: 5 },
  { version: "firered", label: "Pokémon FireRed", pokedexId: 2 },
  { version: "leafgreen", label: "Pokémon LeafGreen", pokedexId: 2 },
  { version: "emerald", label: "Pokémon Emerald", pokedexId: 4 },
  { version: "ruby", label: "Pokémon Ruby", pokedexId: 4 },
  { version: "sapphire", label: "Pokémon Sapphire", pokedexId: 4 },
  { version: "crystal", label: "Pokémon Crystal", pokedexId: 3 },
  { version: "gold", label: "Pokémon Gold", pokedexId: 3 },
  { version: "silver", label: "Pokémon Silver", pokedexId: 3 },
  { version: "yellow", label: "Pokémon Yellow", pokedexId: 2 },
  { version: "red", label: "Pokémon Red", pokedexId: 2 },
  { version: "blue", label: "Pokémon Blue", pokedexId: 2 },
];
