/**
 * Games supported by the Team Randomizer, mapped to their PokéAPI regional
 * Pokédex. Shared between the server action and the client UI.
 */
export const RANDOMIZER_GAMES: { version: string; label: string; pokedexId: number }[] = [  { version: "scarlet", label: "Pokémon Scarlet", pokedexId: 25 },
  { version: "violet", label: "Pokémon Violet", pokedexId: 25 },
  { version: "legends-arceus", label: "Pokémon Legends: Arceus", pokedexId: 24 },
  { version: "sword", label: "Pokémon Sword", pokedexId: 20 },
  { version: "shield", label: "Pokémon Shield", pokedexId: 20 },
  { version: "brilliant-diamond", label: "Pokémon Brilliant Diamond", pokedexId: 5 },
  { version: "shining-pearl", label: "Pokémon Shining Pearl", pokedexId: 5 },
  { version: "lets-go-pikachu", label: "Let's Go, Pikachu!", pokedexId: 2 },
  { version: "lets-go-eevee", label: "Let's Go, Eevee!", pokedexId: 2 },
  { version: "ultra-sun", label: "Pokémon Ultra Sun", pokedexId: 16 },
  { version: "ultra-moon", label: "Pokémon Ultra Moon", pokedexId: 16 },
  { version: "sun", label: "Pokémon Sun", pokedexId: 15 },
  { version: "moon", label: "Pokémon Moon", pokedexId: 15 },
  { version: "omega-ruby", label: "Pokémon Omega Ruby", pokedexId: 14 },
  { version: "alpha-sapphire", label: "Pokémon Alpha Sapphire", pokedexId: 14 },
  { version: "x", label: "Pokémon X", pokedexId: 11 },
  { version: "y", label: "Pokémon Y", pokedexId: 11 },
  { version: "black-2", label: "Pokémon Black 2", pokedexId: 9 },
  { version: "white-2", label: "Pokémon White 2", pokedexId: 9 },
  { version: "black", label: "Pokémon Black", pokedexId: 8 },
  { version: "white", label: "Pokémon White", pokedexId: 8 },
  { version: "heartgold", label: "Pokémon HeartGold", pokedexId: 7 },
  { version: "soulsilver", label: "Pokémon SoulSilver", pokedexId: 7 },
  { version: "platinum", label: "Pokémon Platinum", pokedexId: 6 },
  { version: "diamond", label: "Pokémon Diamond", pokedexId: 5 },
  { version: "pearl", label: "Pokémon Pearl", pokedexId: 5 },
  { version: "firered", label: "Pokémon FireRed", pokedexId: 2 },
  { version: "leafgreen", label: "Pokémon LeafGreen", pokedexId: 2 },
  { version: "emerald", label: "Pokémon Emerald", pokedexId: 4 },
  { version: "ruby", label: "Pokémon Ruby", pokedexId: 4 },
  { version: "sapphire", label: "Pokémon Sapphire", pokedexId: 4 },
  { version: "crystal", label: "Pokémon Crystal", pokedexId: 3 },
  { version: "gold", label: "Pokémon Gold", pokedexId: 3 },
  { version: "silver", label: "Pokémon Silver", pokedexId: 3 },
  { version: "yellow", label: "Pokémon Yellow", pokedexId: 2 },
  { version: "red", label: "Pokémon Red", pokedexId: 2 },
  { version: "blue", label: "Pokémon Blue", pokedexId: 2 },
];

/**
 * Starter Pokémon for each game version, as national Pokédex species IDs.
 * The randomizer deals exactly one of these (your starter) plus five
 * non-starters. Single-entry lists are games with a fixed starter.
 */
export const GAME_STARTERS: Record<string, number[]> = {
  scarlet: [906, 909, 912],
  violet: [906, 909, 912],
  "legends-arceus": [722, 155, 501],
  sword: [810, 813, 816],
  shield: [810, 813, 816],
  "brilliant-diamond": [387, 390, 393],
  "shining-pearl": [387, 390, 393],
  diamond: [387, 390, 393],
  pearl: [387, 390, 393],
  platinum: [387, 390, 393],
  "lets-go-pikachu": [25],
  "lets-go-eevee": [133],
  "ultra-sun": [722, 725, 728],
  "ultra-moon": [722, 725, 728],
  sun: [722, 725, 728],
  moon: [722, 725, 728],
  "omega-ruby": [252, 255, 258],
  "alpha-sapphire": [252, 255, 258],
  ruby: [252, 255, 258],
  sapphire: [252, 255, 258],
  emerald: [252, 255, 258],
  x: [650, 653, 656],
  y: [650, 653, 656],
  "black-2": [495, 498, 501],
  "white-2": [495, 498, 501],
  black: [495, 498, 501],
  white: [495, 498, 501],
  heartgold: [152, 155, 158],
  soulsilver: [152, 155, 158],
  gold: [152, 155, 158],
  silver: [152, 155, 158],
  crystal: [152, 155, 158],
  firered: [1, 4, 7],
  leafgreen: [1, 4, 7],
  red: [1, 4, 7],
  blue: [1, 4, 7],
  yellow: [25],
};
